# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Balance.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMaximumSize(QtCore.QSize(500, 450))
        MainWindow.setStyleSheet("background-color: rgb(204, 204, 204);\n"
"background-image: url(:/image/images11.jpg);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 81))
        self.label.setMaximumSize(QtCore.QSize(521, 81))
        self.label.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 61, 41))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.Female = QtWidgets.QCheckBox(self.centralwidget)
        self.Female.setGeometry(QtCore.QRect(100, 120, 70, 31))
        self.Female.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"")
        self.Female.setObjectName("Female")
        self.Male = QtWidgets.QCheckBox(self.centralwidget)
        self.Male.setGeometry(QtCore.QRect(230, 120, 70, 31))
        self.Male.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.Male.setObjectName("Male")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 111, 41))
        self.label_3.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.Height = QtWidgets.QLineEdit(self.centralwidget)
        self.Height.setGeometry(QtCore.QRect(30, 210, 251, 41))
        self.Height.setObjectName("Height")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 210, 101, 41))
        self.label_4.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.CC = QtWidgets.QPushButton(self.centralwidget)
        self.CC.setGeometry(QtCore.QRect(30, 260, 91, 31))
        self.CC.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";\n"
"")
        self.CC.setObjectName("CC")
        self.TT = QtWidgets.QPushButton(self.centralwidget)
        self.TT.setGeometry(QtCore.QRect(140, 260, 91, 31))
        self.TT.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.TT.setObjectName("TT")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 320, 181, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 360, 421, 61))
        self.label_6.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Height to fit Weight"))
        self.label.setText(_translate("MainWindow", " Ideal wieght calculator"))
        self.label_2.setText(_translate("MainWindow", "เพศ:"))
        self.Female.setText(_translate("MainWindow", "  หญิง"))
        self.Male.setText(_translate("MainWindow", "  ชาย"))
        self.label_3.setText(_translate("MainWindow", "Height"))
        self.label_4.setText(_translate("MainWindow", "cm."))
        self.CC.setText(_translate("MainWindow", "คำนวณ"))
        self.TT.setText(_translate("MainWindow", "รีเซ็ต"))
        self.label_5.setText(_translate("MainWindow", "*่ผลลัพท์ที่ได้จากการคำนวน"))
        self.CC.clicked.connect(self.calculate)
        self.TT.clicked.connect(self.newsys)

    def newsys(self):
        self.Height.setText("")
        self.label_6.setText("")
    def calculate(self):
        if self.Female.isChecked():
            self.total = (float(float(float(self.Height.text()) - float(150)) * float(0.7)) + float(40))
            self.label_6.setText(str(f"{self.total} Kg."))
        elif self.Male.isChecked():
            self.total = (float(float(float(self.Height.text()) - float(150)) * float(0.7)) + float(50))
            self.label_6.setText(str(f"{self.total} Kg."))


import image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

#โปรแกรมมี buk  นิหน่อยนะคับ
